name: Main Branch CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with: 
        node-version: 24
    - run: npm -g install @duckdb/node-api dotenv lodash
